### ISSUE TITLE
[REQUEST] Possility to provide IP and Mac Address

### ISSUE THREAD

**Issue by wikijm** [alive-corpse/esbroadlink#1]
Hi @alive-corpse,

First of all, thanks for your work 😃 

I was wondering if you could add the following arguments (to be filled manually):

- IP address
- MAC address

Thanks in advance for your answer.

Sincerely,
WikiJM

**Comment by alive-corpse** [comment]
Hi! I made this piece of code for my own using, so it's like a draft. :) And I used it for some time, untill I found this project: https://github.com/mjg59/python-broadlink
It perfectly fits for all of my needs. I doesn't need to support my library anymore and I can recommend you to use this founded project! Have a nice day! :)

**Comment by wikijm** [comment]
Hi @alive-corpse,

Thanks for your very quick answer.
Indeed, mjg59/python-brooadlink project feets my needs.

I'll close this issue.

Have a nice day :smile:
